---
deployment:
  tasks:
    # Alkalmazás kódja a Node.js app könyvtárába
    - export APPPATH=/home/dmf/koncert24-app
    - /bin/mkdir -p $APPPATH
    - /bin/cp -R * $APPPATH/
    # Public fájlok a domain mappájába
    - export PUBLICPATH=/home/dmf/public_html/koncert24.hu
    - /bin/mkdir -p $PUBLICPATH
    - /bin/cp -R public/* $PUBLICPATH/
    # A cPanel Node.js App automatikusan kezeli az npm install-t és restart-ot
