---
deployment:
  tasks:
    # Node.js alkalmazás deploy-olása
    - export DEPLOYPATH=/home/dmf/koncert24-app
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R * $DEPLOYPATH
    - cd $DEPLOYPATH
    - npm install --production
    # PM2 restart (ha használod)
    # - pm2 restart koncert24
